SUNET/eduid-dashboard

eduiddashboard/locale/eduid-dashboard.pot, eduiddashboard/locale/en/LC_MESSAGES/eduid-dashboard.po, eduiddashboard/locale/sv/LC_MESSAGES/eduid-dashboard.po, eduiddashboard/static/css/screen.css, eduiddashboard/templates/wizards/basewizard.jinja2, eduiddashboard/views/nins.py
See
https://project.nordu.net/browse/EDUID-184
=> Eperez bug 184

eduiddashboard/static/css/screen.css
Make the wizard usable in small devices
=> responsive wizard

eduiddashboard/static/css/screen.css
Reverts SUNET/eduid-dashboard#33
=> Revert "responsive wizard"

eduiddashboard/static/css/screen.css
Fixing the wizard style for small devices
=> fixing the wizard for small devices

.travis.yml, MANIFEST.in, eduiddashboard/__init__.py, eduiddashboard/emails.py, eduiddashboard/stats.py, eduiddashboard/templates/base.jinja2, eduiddashboard/validators.py, eduiddashboard/verifications.py, eduiddashboard/views/emails.py, eduiddashboard/views/mobiles.py, eduiddashboard/views/nins.py, eduiddashboard/views/personal.py, eduiddashboard/views/portal.py, eduiddashboard/views/postal_address.py, eduiddashboard/views/security.py, eduiddashboard/views/verifications.py, setup.py
Fixed statistics gathering branch.
=> Ft stathat2

eduiddashboard/tests/test_views_nins.py, eduiddashboard/views/portal.py
=> Eperez fix tests

eduiddashboard/middleware.py, eduiddashboard/static/js/eduid-wizards.js, eduiddashboard/static/js/forms-helper-functions.js, eduiddashboard/static/js/profile.js, eduiddashboard/static/js/tabbed-form.js, eduiddashboard/static/js/tablelist-form.js, eduiddashboard/static/js/userstatus.js, eduiddashboard/templates/base.jinja2, eduiddashboard/templates/profile.jinja2, eduiddashboard/tests/test_views_emails.py, eduiddashboard/tests/test_views_mobiles.py, eduiddashboard/tests/test_views_nins.py, eduiddashboard/views/__init__.py, eduiddashboard/views/nins.py, eduiddashboard/views/security.py
=> fix some regressions

eduiddashboard/locale/eduid-dashboard.pot, eduiddashboard/locale/en/LC_MESSAGES/eduid-dashboard.po, eduiddashboard/locale/sv/LC_MESSAGES/eduid-dashboard.po, eduiddashboard/validators.py
Anders Lördal reported that the message was wrong,. "None"
=> fix message for successful validation of nin by mobile

eduiddashboard/tests/test_views_password.py, eduiddashboard/views/security.py, setup.py
This fixes the issue with the local variable 'password' being referenced before assignment in eduiddashboard.views.security: generate_suggested_password.
=> Fix password reference bug

eduiddashboard/tests/test_views_emails.py, eduiddashboard/verifications.py
This should fix the issue with certain users that manage to "steal" their own email address, nin or phone number and thereby removing it from their account.
=> Do not allow stealing from ourself

eduiddashboard/static/css/dashboard.css
=> wizard with new design

eduiddashboard/locale/eduid-dashboard.pot, eduiddashboard/locale/en/LC_MESSAGES/eduid-dashboard.po, eduiddashboard/locale/es/LC_MESSAGES/eduid-dashboard.po, eduiddashboard/locale/sv/LC_MESSAGES/eduid-dashboard.po, eduiddashboard/tests/test_views_nins.py, eduiddashboard/validators.py
fix bug in wizard where you could add twice the same NIN, with a dash or space, one confirmed and one unconfirmed
=> fix bug in wizard where you could add twice the same NIN

eduiddashboard/views/nins.py
if the user already have a verified NiN
=> Normalize NiN and dont send verification code

config-templates/development.ini, eduiddashboard/__init__.py, eduiddashboard/static/css/dashboard.css, eduiddashboard/static/js/mobilemenu.js, eduiddashboard/templates/base.jinja2, eduiddashboard/templates/error404.jinja2, eduiddashboard/templates/error500.jinja2, eduiddashboard/templates/mobiles-form.jinja2, eduiddashboard/templates/profile.jinja2, eduiddashboard/testing.py
=> modals with new design

config-templates/development.ini, eduiddashboard/__init__.py, eduiddashboard/templates/nins-form.jinja2, eduiddashboard/templates/profile.jinja2, eduiddashboard/testing.py, eduiddashboard/tests/test_views_nins.py, eduiddashboard/validators.py, eduiddashboard/views/nins.py, eduiddashboard/views/portal.py
Setting to disable NIN verification through Mina Meddelanden
=> Eperez config mm 2

eduiddashboard/static/css/dashboard.css, eduiddashboard/static/js/basewizard.js, eduiddashboard/static/js/forms-helper-functions.js
Fixing design issues reported in the mailing list
=> Eperez new design 3

eduiddashboard/static/css/dashboard.css, eduiddashboard/templates/passwords-form.jinja2
fixing the layout of the change password modal
=> Eperez newdesign

eduiddashboard/tests/test_verify.py, eduiddashboard/verifications.py
I expect to continue with NIN and phone code tomorrow, but thought it might be easier to review one piece at a time. If you concur, please merge into your eperez-newusers branch.
After we have solid regression tests in place, my idea is to manually (as in: using meld rather than git merge) merge the verifications code into master as a first piece of the eperez-newuser merge.
=> Refactor email-verification code.

eduiddashboard/tests/test_verify.py, eduiddashboard/verifications.py
=> Refactor phone verification code.

eduiddashboard/scripts/fallback_letter_proofing.py, eduiddashboard/tests/test_verify.py, eduiddashboard/verifications.py, eduiddashboard/views/nins.py, eduiddashboard/views/security.py
Last piece. I will now try to manually move this code to a new branch from master.
=> Ft refactor verifications

eduiddashboard/utils.py
in response to a sentry caught exception
=> disable check_sync when modified_ts was None

eduiddashboard/testing.py, eduiddashboard/tests/test_views_emails.py, eduiddashboard/tests/test_views_mobiles.py, eduiddashboard/verifications.py, eduiddashboard/views/__init__.py, eduiddashboard/views/emails.py, eduiddashboard/views/mobiles.py, eduiddashboard/views/nins.py
Using new users in ActionViews. Basically, in eduiddashboard.views.BaseActionsViews.__init__ I set `self.user = get_session_user(self.request)`, and then the methods in the derived view classes have newly fetched new user objects in self.user in their methods.
=> Eperez newusers staging

eduiddashboard/tests/test_views_mobiles.py, eduiddashboard/views/__init__.py, eduiddashboard/views/mobiles.py
and relating problems such as when the user tries to remove
a mobile which index is out of range.
A small fix for a bug in resend_code_action is also included.
=> Fixes for removal of primary mobile,

eduiddashboard/saml2/views.py
When the user has either cleared her/his cookies, closed and opened
the browser, or in some other way lost the session information needed
a error page with a status code 500 is displayed.
A more user-friendly experience is achieved if the user is redirected so
that a new login is performed.
=> When session information is absent - perform a new login

eduiddashboard/views/security.py
But we still need to be able to support the legacy
password reset codes for some time to come.
=> Reset codes are now identified by eppn

eduiddashboard/__init__.py, eduiddashboard/middleware.py, eduiddashboard/tests/test_views_password.py, eduiddashboard/views/portal.py, eduiddashboard/views/security.py
Use the authentication microservice for reauthentication, both for changing password and for account termination.
=> Eperez reauthn term

eduiddashboard/templates/base.jinja2
logout button now POSTs to the authn service
=> logout button now POSTs to the authn service

eduiddashboard/tests/test_views_password.py
I thought changing the markup in the logout button would not affect the tests... Of course it does
=> Eperez logout

eduiddashboard/templates/nins-form.jinja2, eduiddashboard/templates/profile.jinja2
Hook up the oidc proofing component into the dashboard
=> hook the oidc proofing app

.travis.yml, config-templates/development.ini, eduiddashboard/__init__.py, eduiddashboard/templates/base.jinja2, eduiddashboard/templates/profile.jinja2
Configure which js bundle is pulled from the dashboard
=> configure which js bundle to use in the dashboard

config-templates/development.ini, eduiddashboard/__init__.py, eduiddashboard/permissions.py, eduiddashboard/templates/profile.jinja2
Allow configuration of which js (webpack) bundles are selected for each user session, for testing new features in a real environment
=> Eperez config jsbundles

config-templates/development.ini, eduiddashboard/__init__.py, eduiddashboard/permissions.py, eduiddashboard/templates/base.jinja2, eduiddashboard/templates/profile.jinja2
=> Eperez config jsconfig

eduiddashboard/templates/base.jinja2
Internationalization of freja component
=> add selected lang code to html so the freja component can access it

eduiddashboard/locale/eduid-dashboard.pot, eduiddashboard/locale/en/LC_MESSAGES/eduid-dashboard.po, eduiddashboard/locale/es/LC_MESSAGES/eduid-dashboard.po, eduiddashboard/locale/sv/LC_MESSAGES/eduid-dashboard.po, eduiddashboard/templates/base.jinja2
Markup and translatable strings for the "change dashboard version" link in the old dashboard
=> Eperez choose new
